In [28]:
import numpy as np
import pandas as pd
import math
def myfun(x):
    p=math.pow(x,0.5)
    return p
ss_frame=pd.read_csv('num.csv')
s=np.array(ss_frame)
print(s)
p=[]
n=0
gh=0
while n<len(s):
    j=myfun(s[n][0])+myfun(s[n][1])+myfun(s[n][2])*4
    p.append(j)
    gh+=j
    n+=1
print(p)
print(len(p))
print(gh)

[[1 3 2]
 [3 5 4]
 [5 7 6]
 [7 9 8]]
[8.388905057061258, 11.968118785068667, 14.679778259697091, 16.959459810049353]
4
51.996261911876374
